apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  template:
    spec:
      initContainers:
        - name: curl
          image: curlimages/curl
          command:
            - sh
            - -c
          args:
<<<<<<< HEAD
            - mkdir -p /data/mods; curl -o /data/mods/pack.mrpack -L https://github.com/chocolalatte/Minecraft-Server/raw/refs/heads/main/pack.mrpack;
=======
            - mkdir -p /data/mods; curl -o /data/mods/pack.mrpack -L https://github.com/chocolalatte/Minecraft-Server/raw/refs/heads/main/base/pack.mrpack;
>>>>>>> main
          volumeMounts:
            - name: datadir
              mountPath: /data
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: minecraft-datadir
