apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lily
nameSuffix: -main
commonLabels:
  app: minecraft-main

resources:
  - ../../base

patches:
  - path: deployment-main.yml
