apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 1000m
              memory: 10Gi
          volumeMounts:
            - name: datadir
              mountPath: /data
          env:
            - name: EULA
              value: "TRUE"
            - name: MEMORY
              value: "9G"
            - name: JVM_XX_OPTS
              value: "-Xms9G -Xmx9G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
            - name: ENABLE_RCON
              value: "true"
            - name: VERSION
              value: 1.20.1
            - name: FABRIC_LOADER_VERSION
              value: "0.16.10"
            - name: MOTD
              value: Running %MODPACK_NAME% version %env:MODPACK_VERSION%
            - name: DEBUG
              value: "FALSE"
            - name: MODPACK_PLATFORM
              value: MODRINTH
            - name: MODRINTH_MODPACK
              value: "/data/mods/pack.mrpack"
            - name: MODPACK_NAME
              value: "silly-server-pack"
            - name: MODPACK_VERSION
              value: "0.0.1"
            - name: ICON
              value: "https://github.com/chocolalatte/Minecraft-Server/raw/refs/heads/dev/imports/icon.png"
            - name: DIFFICULTY
              value: normal
            - name: SEED
              value: "4668041971450772477"
            - name: ENABLE_WHITELIST
              value: "TRUE"
            - name: WHITELIST
              value: |
                Cinna_Chocolate
                Xx_Wi11ow_xX
                spookme420
                Topilpop
                AstrumHero
                Java861
                Sunkissedmist
                cb74b280-b61c-4f59-91bf-6d07b7b5f616
            - name: OPS
              value: Cinna_Chocolate
          ports:
            - name: minecraft
              containerPort: 25565
              protocol: TCP
            - name: rcon
              containerPort: 25575
              protocol: TCP
            - name: voicechat
              containerPort: 24454
              protocol: UDP
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: minecraft-datadir
      readinessProbe:
        tcpSocket:
          port: 25565
        initialDelaySeconds: 30
        periodSeconds: 5
        failureThreshold: 10
        successThreshold: 1
        timeoutseconds: 1
      livenessProbe:
        tcpSocket:
          port: 25565
        initialDelaySeconds: 30
        periodSeconds: 5
        failureThreshold: 10
        successThreshold: 1
        timeoutseconds: 1
