apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
spec:
  template:
    spec:
      initContainers:
      - name: curl
        image: curlimages/curl
        command: 
        - sh
        - -c
        args:
        - mkdir -p /data/mods; curl -o /data/mods/pack.mrpack -L https://github.com/chocolalatte/Minecraft-Server/raw/refs/heads/dev/base/pack.mrpack;
        volumeMounts:
        - name: datadir
          mountPath: /data
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: minecraft-datadir
      containers:
      - name: minecraft
        image: itzg/minecraft-server:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
        volumeMounts:
        - name: datadir
          mountPath: /data
        env:
        - name: MEMORY
          value: "3G"
        - name: JVM_XX_OPTS
          value: "-Xms3G -Xmx3G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true"
        - name: MOTD
          value: Running %MODPACK_NAME% version %env:MODPACK_VERSION% (dev)
        - name: OPS
          value: |
            Cinna_Chocolate
            Xx_Wi11ow_xX
            spookme420
            Topilpop
            AstrumHero
            Java4386
            cb74b280-b61c-4f59-91bf-6d07b7b5f616
        ports:
        - name: minecraft
          containerPort: 25565
          protocol: TCP
        - name: rcon
          containerPort: 25575
          protocol: TCP
        - name: voicechat
          containerPort: 24454
          protocol: UDP
      volumes:
      - name: datadir
        persistentVolumeClaim:
          claimName: minecraft-datadir
      readinessProbe:
        tcpSocket:
          port: 25565
        initialDelaySeconds: 30
        periodSeconds: 5
        failureThreshold: 10
        successThreshold: 1
        timeoutseconds: 1
      livenessProbe:
        tcpSocket:
          port: 25565
        initialDelaySeconds: 30
        periodSeconds: 5
        failureThreshold: 10
        successThreshold: 1
        timeoutseconds: 1
