apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lily
nameSuffix: -dev
commonLabels:
  app: minecraft-dev

resources:
  - ../../base

patches:
  - path: deployment-dev.yml
  - path: pvc-dev.yml
  - path: service-dev.yml
