---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-datadir
  labels:
    app: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: lvms-vg1
