---
apiVersion: v1
kind: Service
metadata:
  name: service
  labels:
    app: minecraft
spec:
  type: NodePort
  ports:
    - protocol: TCP
      targetPort: 25565
      port: 25565
      nodePort: 30010
      name: minecraft
    - protocol: TCP
      targetPort: 25575
      port: 25575
      nodePort: 30011
      name: rcon
    - protocol: UDP
      targetPort: 30002
      port: 30002
      nodePort: 30012
      name: voice
  selector:
    app: minecraft
